ENGINES = {

    "local_router_primary": {
        "provider": "ollama",
        "model_env": "OLLAMA_PRIMARY_MODEL",
        "default_model": "qwen2.5:3b",
        "role": "routing",
        "private": True,
        "web_search": False,
        "creative_writing_quality": 1,
        "available": True,
    },

    "local_agent": {
        "provider": "ollama",
        "model_env": "OLLAMA_AGENT_MODEL",
        "default_model": "qwen2.5:7b-instruct",
        "role": "general_local_cognition",
        "private": True,
        "web_search": False,
        "creative_writing_quality": 2,
        "available": True,
    },

    "local_reasoner_fallback": {
        "provider": "ollama",
        "model_env": "OLLAMA_FALLBACK_MODEL",
        "default_model": "qwen3:8b",
        "role": "heavy_local_reasoning",
        "private": True,
        "web_search": False,
        "reasoning_quality": 4,
        "creative_writing_quality": 4,
        "translation_quality": 3,
        "speed": 1,
        "available": True,
    },

    "cloud_fast": {
        "provider": "openai",
        "model": "gpt-5.4-mini",
        "role": "cloud_fast",
        "private": False,
        "web_search": False,
        "reasoning_quality": 4,
        "creative_writing_quality": 4,
        "translation_quality": 5,
        "speed": 3,
        "available": True,
    },

    "cloud_deep": {
        "provider": "openai",
        "model": "gpt-5.5",
        "role": "cloud_deep_reasoning",
        "private": False,
        "web_search": False,
        "reasoning_quality": 5,
        "creative_writing_quality": 5,
        "translation_quality": 5,
        "speed": 1,
        "available": True,
    },

    "cloud_web_fast": {
        "provider": "openai",
        "model": "gpt-5.4-mini",
        "role": "web_fast",
        "private": False,
        "web_search": True,
        "reasoning_quality": 4,
        "creative_writing_quality": 4,
        "translation_quality": 4,
        "speed": 2,
        "available": True,
    },

    "cloud_web_deep": {
        "provider": "openai",
        "model": "gpt-5.5",
        "role": "web_deep",
        "private": False,
        "web_search": True,
        "reasoning_quality": 5,
        "creative_writing_quality": 5,
        "translation_quality": 4,
        "speed": 1,
        "available": True,
    },
    
    "local_vision_sensei": {
        "provider": "ollama",
        "model_env": "OLLAMA_VISION_MODEL",
        "default_model": "llava:7b",
        "role": "vision",
        "modalities": ["image", "text"],
        "strengths": [
            "plant_photo_analysis",
            "bonsai_structure",
            "visual_diagnosis",
        ],
        "private": True,
        "web_search": False,
        "creative_writing_quality": 2,
        "available": False,
    },

    "cloud_vision": {
        "provider": "openai",
        "model": "gpt-5.4-mini",
        "role": "vision",
        "modalities": ["image", "text"],
        "strengths": [
            "image_understanding",
            "plant_photo_analysis",
            "scene_analysis",
        ],
        "private": False,
        "web_search": False,
        "creative_writing_quality": 2,
        "available": False,
    },

    "local_audio_transcriber": {
        "provider": "local",
        "model_env": "LOCAL_STT_MODEL",
        "default_model": "whisper.cpp/base",
        "role": "speech_to_text",
        "modalities": ["audio"],
        "strengths": [
            "voice_commands",
            "dictation",
            "offline_transcription",
        ],
        "private": True,
        "web_search": False,
        "creative_writing_quality": 2,
        "available": False,
    },

    "cloud_audio_transcriber": {
        "provider": "openai",
        "model": "gpt-4o-transcribe",
        "role": "speech_to_text",
        "modalities": ["audio"],
        "strengths": [
            "accurate_transcription",
            "voice_commands",
            "multilingual_audio",
        ],
        "private": False,
        "web_search": False,
        "creative_writing_quality": 2,
        "available": False,
    },
}